# Generated by Django 4.2.21 on 2025-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Заголовок', max_length=255, verbose_name='Заголовок страницы')),
                ('page_nav', models.CharField(default='Ссылка', max_length=255, verbose_name='Ссылка')),
                ('page_nav_position', models.IntegerField(default=1, help_text='большее - число правее, 0 - исключить из навигации', verbose_name='Приоритет ссылки в навигации (0 - исключить)')),
                ('page_content', models.TextField(default='<a id="top_of _page" href="#h1" class="card-link">на начало</a>   <h6 class="card-subtitle mb-2 text-body-secondary ">   <a id="h1">Я</a></h6>   <p class="card-text">ФИО: Мэри <br/> Номер телефона: +88 888-888-88-88 <br/> Электронка: 88@77.ru <br/> Резюме: <br/> Выпускник старшей школы, знаю три языка, не умею играть на виалончели, умею писать левой рукой и стоять на одной ноге. </p><br/>  <img src="/static/images/me.png"  height="30px">    <a href="#top_of _page" class="card-link>вернуься в начало</a>', verbose_name='Основное содержание страницы')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата Записи')),
            ],
            options={
                'verbose_name': 'Текущая страница',
                'verbose_name_plural': 'Все мои страницы',
                'ordering': ('-page_nav_position',),
            },
        ),
    ]
