# Generated by Django 4.2.21 on 2025-05-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Востоковедение', max_length=255, verbose_name='Образовательная программа')),
                ('a', models.CharField(default='Мэри', max_length=255, verbose_name='Имя студента')),
                ('b', models.CharField(default='японский', help_text='мы все учим восточные языки', max_length=255, verbose_name='Язык')),
                ('c', models.IntegerField(choices=[(1, 'первый'), (2, 'второй'), (3, 'третий'), (4, 'четвертый'), (5, 'пятый')], default=3, verbose_name='Год обучения')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': 'Таблица_студентов',
                'verbose_name_plural': 'Таблицы_студентов',
                'ordering': ('-pk',),
            },
        ),
        migrations.DeleteModel(
            name='AbcModel',
        ),
    ]






